V1:
  include: [['10X232_1', '10X232_2', '10X232_3', '10X232_4']]
  
  params:
    n_genes: 1000 
  execution:
    n_cpus: 56
    memory: 750
  steps: doublets, poisson_pooling, nn, embeddings, aggregate, export

Midbrain:
  include: [['10X232_3', '10X232_4']]

Cerebellum:
  include: [['10X232_1', '10X232_2']]